---
title: "GLM"
output: html_document
---

```{r message = FALSE}
library(class)
library(dplyr)
library(caret)
library (ROCR)
library(kernlab)
library(DMwR)
source("funcs.R")
```


```{r load_data, message=FALSE, warning=FALSE, echo=TRUE}

dataTrain_origin <- readRDS("datasetTrainModeloClasificador.rds")
dataTest_origin <- readRDS("datasetTestModeloClasificador.rds")

```


```{r}

dataTrain <- dataTrain_origin %>% dplyr::select(-SalePrice)
dataTest <- dataTest_origin %>% dplyr::select(-SalePrice)

```


```{r}

remove <- c('GrupoPrecio')
col_to_factor <- colnames(dataTrain) [! colnames(dataTrain) %in% remove]

dataTrain <- dataTrain %>% as_factor_all(col_to_factor)
dataTest <- dataTest %>% as_factor_all(col_to_factor)

XTrain <- dataTrain %>% dplyr::select(-GrupoPrecio)
YTrain <- dataTrain$GrupoPrecio

XTest <- dataTest %>% dplyr::select(-GrupoPrecio)
YTest <- dataTest$GrupoPrecio

```

### ENTRENAMIENTO, OPTIMIZACIÓN Y EVALUACIÓN DEL MODELO

```{r}

#Normalización
ctrNorm <- preProcess(x = XTrain, method = c("center", "scale"))

dataTrainNorm <- predict(ctrNorm, dataTrain)

#Entrenamiento y busqueda de k más optimo
set.seed(400)
ctrl <-  trainControl(method = "repeatedcv", repeats=3, classProbs = TRUE, summaryFunction = twoClassSummary, savePredictions = TRUE, sampling = "smote")
glm <- train(GrupoPrecio ~ ., data = dataTrainNorm, method = "glm", trControl = ctrl, family = "binomial")
(glm)


XTestNorm <- predict(ctrNorm, XTest)
pred <- predict(glm, newdata = XTestNorm )

cm <- confusionMatrix(pred, YTest, mode = "prec_recall" )
(cm)
tab_test <- table(pred, YTest, dnn = c("Actual", "Predichos"))
draw_confusion_matrix(tab_test, "Actual", "Predichos")

```

```{r ,echo=FALSE,message=FALSE, warning=FALSE, fig.height=18, fig.width=18, multi.col=T}
res <-evalm(list(glm),gnames = c('glm'),rlinethick=0.8,fsize=30, showplots = TRUE , bins=20, plots = c("prg"))

```

```{r ,echo=FALSE,message=FALSE, warning=FALSE, fig.height=18, fig.width=18, multi.col=T}
res <-evalm(list(glm),gnames = c('glm'),rlinethick=0.8,fsize=30, showplots = TRUE , bins=20, plots = c("pr"))

```

```{r ,echo=FALSE,message=FALSE, warning=FALSE, fig.height=18, fig.width=18, multi.col=T}
res <-evalm(list(glm),gnames = c('glm'),rlinethick=0.8,fsize=30, showplots = TRUE , bins=20, plots = c("r"))

```

```{r ,echo=FALSE,message=FALSE, warning=FALSE, fig.height=18, fig.width=18, multi.col=T}
res <-evalm(list(glm),gnames = c('glm'),rlinethick=0.8,fsize=30, showplots = TRUE , bins=20, plots = c("cc"))

```

```{r , message=FALSE, warning=FALSE, echo=TRUE}

saveRDS(glm, "glm.rds")

```

