---
title: "K Nearest Neighbors - KNN"
---

```{r load_libraries, message=FALSE, warning=FALSE, echo=FALSE}

library(dplyr)
library(class)
library(caret)
library(ggplot2)
library(arules)
library(RColorBrewer)
source("utils.R")

library(plotly)

source("process_nan.R")
source("split_data.R")
```


Cargamos los datos:

```{r load_data, message=FALSE, warning=FALSE, echo=TRUE}

df_total <- read.csv(file = 'dataset/TrainTestDefinitivo1.csv')
#df_total <- read.csv(file = 'dataset/dataset1.csv')

```

```{r discretize_var_pred, message=FALSE, warning=FALSE, echo=TRUE}

v = discretize(df_total$SalePrice, breaks = 3, onlycuts =TRUE, infinity = TRUE)

df_total$GrupoPrecio = cut(df_total$SalePrice, v)

levels(df_total$GrupoPrecio) = c('barato', 'normal', 'caro')




df_total$GrupoPrecio[which(mtcars$GrupoPrecio == 0)] <- 'barato'
df_total$GrupoPrecio[which(mtcars$GrupoPrecio == 1)] <- 'normal'
df_total$GrupoPrecio[which(mtcars$GrupoPrecio == 2)] <- 'caro'
df_total$GrupoPrecio <- as.factor(df_total$GrupoPrecio)

fig <- plot_ly(df_total, x = ~TotalSF, y = ~LotArea, z = ~GrLivArea, color = ~GrupoPrecio, colors = c('#BF382A', '#00FF00','#0C4B8E'))
fig <- fig %>% add_markers()
fig <- fig %>% layout(scene = list(xaxis = list(title = 'Weight'),
                     yaxis = list(title = 'Gross horsepower'),
                     zaxis = list(title = '1/4 mile time')))

fig
```


```{r choose_cols}

group <- c('GrLivArea', 'LotArea','BedroomAbvGr','SalePrice', 'GrupoPrecio')

group <- c('TotalSF','LotArea','GrLivArea','GrupoPrecio')

df <- df_total %>% select(group)


draw_scatter(df_total,'GrLivArea','SalePrice' )
draw_scatter(df_total,'SalePrice','YrSold')
draw_scatter(df_total,'BsmtFinSF1','SalePrice')
#draw_scatter(df_total,'SalePrice','Neighborhood')

draw_scatter(df_total,'YearBuilt','GrLivArea')
draw_scatter(df_total,'YearBuilt','TotalSF')
draw_scatter(df_total,'YearBuilt','LotArea')

draw_scatter(df_total,'Neighborhood','GrLivArea')
draw_scatter(df_total,'Neighborhood','TotalSF')
draw_scatter(df_total,'Neighborhood','LotArea')
```

```{r eda}

summary(df)
head(df)

```


```{r clean_data}

df <- df[!(is.na(df$GrupoPrecio)),]


(get_cols_nan(df))
#df <- fillNanWithMean(df)
```



Separamos el dataframe en dos partes, una parte para el entrenamiento y otra para el test

```{r split_data, message=FALSE, warning=FALSE, echo=FALSE}

result <- split_data(df, 0.7)

train <- result$blockH
test <- result$blockL

XTrain <- train %>% select(-GrupoPrecio)
YTrain <- train$GrupoPrecio

XTest <- test %>% select(-GrupoPrecio)
YTest <- test$GrupoPrecio



nor <-function(x) { (x -min(x))/(max(x)-min(x))   }

#XTrain <- as.data.frame(lapply(XTrain[,c(1,2,3)], nor))
#XTest <- as.data.frame(lapply(XTest[,c(1,2,3)], nor))


```

Ejecutamos el modelo knn con el parametro k = 13, que nos da la siguiente matriz de confusión
```{r run_model, message=FALSE, warning=FALSE, echo=TRUE}

pr_train <- knn(XTrain, XTrain, cl = YTrain, k=3)
pr_test <- knn(XTrain, XTest, cl = YTrain, k=3)

```

Evaluamos el modelo:
```{r eval_model}

tab_train <- table(pr_train, YTrain, dnn = c("Actual", "Predichos"))
tab_test <- table(pr_test, YTest, dnn = c("Actual", "Predichos"))

accuracy(tab_train)
knn_train_error <- calc_error_rate(predicted.value=pr_train, true.value=YTrain)
(knn_train_error)

accuracy(tab_test)
knn_test_error <- calc_error_rate(predicted.value=pr_test, true.value=YTest)
(knn_test_error)


(tab_test)
draw_confusion_matrix(tab_train, "Actual", "Predichos")
draw_confusion_matrix(tab_test, "Actual", "Predichos")


```

```






